import type { PolicyDefinition, PolicyType } from "../types/policyTypes";

export const POLICY_DEFINITIONS: PolicyDefinition[] = [
  {
    type: "mobileApps",
    label: "Applications",
    namespace: "deviceAppManagement",
    supportsFilters: true,
    supportsIntent: true,
    assignBodyKey: "mobileAppAssignments",
    autopilotDirectPost: false,
    fetchAssignmentsViaExpand: true,
  },
  {
    type: "configurationPolicies",
    label: "Settings Catalog",
    namespace: "deviceManagement",
    supportsFilters: true,
    supportsIntent: false,
    assignBodyKey: "assignments",
    autopilotDirectPost: false,
    fetchAssignmentsViaExpand: false,
  },
  {
    type: "deviceConfigurations",
    label: "Device Configuration",
    namespace: "deviceManagement",
    supportsFilters: true,
    supportsIntent: false,
    assignBodyKey: "assignments",
    autopilotDirectPost: false,
    fetchAssignmentsViaExpand: true,
  },
  {
    type: "deviceCompliancePolicies",
    label: "Compliance",
    namespace: "deviceManagement",
    supportsFilters: true,
    supportsIntent: false,
    assignBodyKey: "assignments",
    autopilotDirectPost: false,
    fetchAssignmentsViaExpand: true,
  },
  {
    type: "groupPolicyConfigurations",
    label: "Admin Templates",
    namespace: "deviceManagement",
    supportsFilters: true,
    supportsIntent: false,
    assignBodyKey: "assignments",
    autopilotDirectPost: false,
    fetchAssignmentsViaExpand: true,
  },
  {
    type: "deviceManagementScripts",
    label: "Platform Scripts",
    namespace: "deviceManagement",
    supportsFilters: false,
    supportsIntent: false,
    assignBodyKey: "deviceManagementScriptAssignments",
    autopilotDirectPost: false,
    fetchAssignmentsViaExpand: true,
  },
  {
    type: "deviceHealthScripts",
    label: "Remediation Scripts",
    namespace: "deviceManagement",
    supportsFilters: true,
    supportsIntent: false,
    assignBodyKey: "assignments",
    autopilotDirectPost: false,
    fetchAssignmentsViaExpand: true,
  },
  {
    type: "windowsAutopilotDeploymentProfiles",
    label: "Autopilot",
    namespace: "deviceManagement",
    supportsFilters: false,
    supportsIntent: false,
    assignBodyKey: "assignments",
    autopilotDirectPost: true,
    fetchAssignmentsViaExpand: true,
  },
  {
    type: "mobileAppConfigurations",
    label: "App Configurations",
    namespace: "deviceAppManagement",
    supportsFilters: true,
    supportsIntent: false,
    assignBodyKey: "mobileAppAssignments",
    autopilotDirectPost: false,
    fetchAssignmentsViaExpand: true,
  },
  {
    type: "deviceManagementIntents",
    label: "Intents",
    namespace: "deviceManagement",
    supportsFilters: false,
    supportsIntent: false,
    assignBodyKey: "assignments",
    autopilotDirectPost: false,
    fetchAssignmentsViaExpand: false,
  },
];

export function getPolicyDefinition(type: PolicyType): PolicyDefinition {
  const def = POLICY_DEFINITIONS.find((d) => d.type === type);
  if (!def) throw new Error(`Unknown policy type: ${type}`);
  return def;
}
